### ISSUE TITLE
OBS 27 seems to crash due to Tuna

### ISSUE THREAD

**Issue by EpicLPer** [univrsal/tuna#123]
**Describe the bug**
OBS released Version 27 as a Release Candidate a few days ago which keeps crashing due to Tuna, at least according to the Crash Log. Sometimes OBS also "bugs the interface out" and, instead of Qt Elements, shows Windows specific ones such as standard Windows Sliders instead of the fancy Qt ones, see Screenshot below.

**To Reproduce**
1. Us OBS 27 RC from their Github Repo
2. Start Tuna Plugin in Tuna Settings
3. Wait a few seconds/minutes
4. Crashes

**Expected behavior**
Starting the Tuna Plugin should not crash OBS as a whole after a few minutes.

**Screenshots**
Some elements that should be from Qt get replaced by Windows default ones. This only occasionally happens but does seem to be caused by Tuna for some reason. Can't 100% confirm tho.
![image](https://user-images.githubusercontent.com/8442196/113676028-43c60100-96bc-11eb-9175-48d45556c757.png)  
Normally it should look like this: 
![image](https://user-images.githubusercontent.com/8442196/113676315-96072200-96bc-11eb-87a1-2d7cad90d211.png)

**Log**
OBS only occasionally mentions "tuna.dll" in it's crashlog, but not always. Usually it just shows "qt5gui.dll" instead, but stopping the Tuna Plugin in Settings seems to make OBS not crash anymore so I suspect heavily it has to do with Tuna.
[OBS Crash Log where it mentions tuna.dll](https://pastebin.com/H792HPsP)  
[OBS Crash Log where it mentions qt5gui.dll](https://pastebin.com/jqtzQKeC)

**Additional context**
Since this is a "Pre-Release" it may be a bug with OBS and not Tuna, but I've seen Tuna a few times in the crashlogs above. I'm gonna submit this bug here before making a full bug report for the OBS team in case it is Tuna related. Sorry for inconvenience in case it isn't :)

**Comment by EpicLPer** [comment]
Any update on this?

**Comment by univrsal** [comment]
Might be because tuna is compiled against an older qt version

**Comment by EpicLPer** [comment]
Seems like that indeed fixed the issue! Nice :)

**Comment by EpicLPer** [comment]
Btw. in case you didn't notice, OBS 27 released yesterday. I haven't confirmed if the bug I saw above also happens on the official version, but going by the info you gave of an old Qt version being at fault I guess it'll be the same there too.  
Would probably be best to release the Tuna version I tested so people aren't getting confused or will open more bug reports for it, as it seems to work flawlessly so far.

**Comment by univrsal** [comment]
I guess this one's fixed

**Comment by EpicLPer** [comment]
> I guess this one's fixed

Technically yes but of course it still has to be released officially :)

**Comment by univrsal** [comment]
I have already released it

**Comment by EpicLPer** [comment]
Oh? On the "Release" download page it still shows the last version of somewhere late 2020 for me, 1.5.4.

**Comment by univrsal** [comment]
yeah but that one never had binaries attached, which I now did.
