### ISSUE TITLE
Song Info Output settings crashing

### ISSUE THREAD

**Issue by AMDITAR** [univrsal/tuna#30]
I have tuna installed on two macs that I regularly use for streaming.  One is running MacOS Mojave and the other is running MacOS Catalina.  On both of them, I cannot change anything related to the Song Info Outputs.  Whenever I make a change, and click Apply and Ok, the changes are discarded.  This includes any actions related to "Add new," "Remove selected," "Edit selected." In other words, whenever I try to add, remove, or edit song info outputs, my changes are immediately discarded. 

Within the Output Editor window, changes to the file directory cause the whole tuna settings window to crash after making the change when clicking Ok, and then I have to click Tools -> Tuna Settings twice to bring the settings window back up.  None of my changes are saved and this happens 100% of the time. 

Also in the Output Editor window if I change any data in the bottom Format Editor string, and click ok, the changes are reflected in the Tuna Preferences window, then I click apply and ok to close the Tuna Preferences window, and my changes are instantly discarded.  When I go back into Tuna Preferences, the settings are back at defaults as if I had not made any changes.  

Everything I have described is 100% reproducible across both my machines. 

OBS 25.0.8 (64 bit) Tuna 1.4.1 (I can't update to the latest version because no mac installer was posted for the latest version). 

Thanks in advance for your help with this critical issue.

**Comment by univrsal** [comment]
Should be fixed with 1.4.2b

**Comment by AMDITAR** [comment]
I installed 1.4.2b and the issue persists as described originally.  I don't see any change in behavior.

**Comment by univrsal** [comment]
I tested all the issues you reported and cannot reproduce any with 1.4.2b on 25.0.8 with macOS 10.15.3, I can't do much more beyond that

**Comment by AMDITAR** [comment]
Perhaps you can help me figure out why the new version is not working by answering some questions I have.  I've reproduced the issue after reinstalling the plugin on two Macs I'm running OBS 25.4.8 on.  One is running MacOS 10.15.5 and the other MacOS 10.14.6.  I've deleted and re-added the plugin files, and I've completely uninstalled and reinstalled OBS and the plugin with the latest versions with no change.  Is it possible that the old version is stuck on my system somehow?  Does tuna save files in any directory besides the main one that the plugin is copied into?  Could there be some permissions issue I'm missing?  

For reference, all I want to do is make the Artist and Song Title appear in the text.  The default is Album and Song Title and I'm unable to change it.  I want to give credit to the artists I play on my stream on screen, and this would be the perfect solution were I able to change that one %a to an %m.  

I'm attaching a video of a screen capture of the issue occurring on MacOS 10.15.5 with OBS 25.4.8 and Tuna 1.4.2b.
[Screen Recording 2020-06-19 at 9.17.06 AM.mp4.zip](https://github.com/univrsal/tuna/files/4804807/Screen.Recording.2020-06-19.at.9.17.06.AM.mp4.zip)

**Comment by univrsal** [comment]
you have to update to obs 25.0.8, they updated the qt version at some point and the plugin expects that qt version

**Comment by AMDITAR** [comment]
Yes, my apologies, I made a typo.  Using 25.0.8 on both machines.  I'm attaching the OBS log here.  

I notice the error "Couldn't write outputs to /Users/tony/.config/outputs.json" at the bottom.  I checked my user directory and I don't have a .config directory.  Do I need to create it manually? 

Thanks in advance for your support. 
[2020-06-19 11-15-00.txt](https://github.com/univrsal/tuna/files/4805341/2020-06-19.11-15-00.txt)

**Comment by AMDITAR** [comment]
I went ahead and created the .config directly manually, and now I can save changes to the metadata string!  
However, the directory change bug persists.  When I try to change the directory for the song.txt file the tuna window crashes and my changes are not saved.  I'm attaching a new OBS log in which I fresh start OBS and try to do that operation and nothing else. 
Excerpted from the bottom: 

> 11:26:11.446: obs-browser: Uncaught (in promise) Something went wrong. (source: https://streamlabs.com/widgets/emote-wall?token=ED94B1C1E8F8A07E32C1:0)
11:26:11.598: obs-browser: Uncaught (in promise) TypeError: Invalid attempt to spread non-iterable instance.
11:26:11.598: In order to be iterable, non-array objects must have a [Symbol.iterator]() method. (source: https://streamlabs.com/mixed/assets/widgets/js/emote-wall.js?id=5d532b002a21d30893dd:2)
[2020-06-19 11-26-07.txt](https://github.com/univrsal/tuna/files/4805405/2020-06-19.11-26-07.txt)

**Comment by AMDITAR** [comment]
I went ahead and created the .config directly manually, and now I can save changes to the metadata string!  
However, the directory change bug persists.  When I try to change the directory for the song.txt file the tuna window crashes and my changes are not saved.  I'm attaching a new OBS log in which I fresh start OBS and try to do that operation and nothing else. 
[2020-06-19 11-26-07.txt](https://github.com/univrsal/tuna/files/4805410/2020-06-19.11-26-07.txt)

**Comment by AMDITAR** [comment]
I just figured that one out as well, it was a MacOS permissions issue.  I had to give OBS "Full Disk Access" in my Security and Privacy settings.  OBS only had access to Desktop, Documents, and Downloads folders by default, and therefore couldn't make or read a file from any other folder, such as my Music folder, where I was trying to move the song.txt file to.  

Thanks for your help.  As a suggestion, more instructions on permissions and directories for installation for the Mac users would be helpful.  I had to do a manual install on my machines because MacOS didn't give your install script full permissions to create all the directories it needed to.

**Comment by univrsal** [comment]
I have no clue how permissions on macOS work, since I do not use it. I have seen other people have issues that prevented them from launching the plugin at all though. The best I can probably do is add a warning that people need to set the permissions manually.

**Comment by d3v1an7** [comment]
Hey all! Can confirm, the only thing I needed to do on https://github.com/univrsal/tuna/releases/tag/v1.4.2 was `mkdir -p ~/.config`. Perhaps this can be added to `install-mac.sh`?

Happy to raise a PR! Unrelated, but also cool to set up a tap and brew forumla for this if you'd like, @univrsal.

**Comment by univrsal** [comment]
The config folder should already be created by the plugin, I don't think it's in the current release though. I've also added CI which builds an *.pkg installer automatically so the script won't be needed anymore.
> Unrelated, but also cool to set up a tap and brew formula for this if you'd like

Sure, although I have decided to drop support for macOS, because I don't use it and it's too much effort. I'll still provide builds, but won't spend any time on trying to fix mac specific issues as long as the plugin compiles.
Nightly builds can be downloaded [here](https://github.com/univrsal/tuna/actions/runs/205864988) and future builds are under the github actions.

**Comment by univrsal** [comment]
I've made some bigger changes and as I said I won't support macOS anymore, but since github actions can build macOS versions for me I'll still offer binaries. Once the latest [run](https://github.com/univrsal/tuna/actions/runs/208704747) you can get a *.pkg installer and test the changes. The installer worked for me and I didn't see any other major issues.
